/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import javax.swing.ImageIcon;

/**
 *
 * @author nmadariaga
 */
public class AcercaDe extends javax.swing.JFrame {

    /**
     * Creates new form AcercaDe
     */
    public AcercaDe() {
        initComponents();
        setIconImage(new  ImageIcon(getClass().getResource("/Imagenes/LogoSE.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setTitle("Acerca de Sistema Experto");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(404, 235));
        setMaximumSize(new java.awt.Dimension(600, 250));
        setMinimumSize(new java.awt.Dimension(600, 250));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoSE_about.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 30, 129, 128);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoUtem_about.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(430, 30, 104, 128);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Sistema Experto");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 30, 200, 40);

        jLabel5.setFont(new java.awt.Font("Noto Sans", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("para la evaluacion de negocios");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(210, 60, 210, 16);

        jLabel6.setFont(new java.awt.Font("Noto Sans", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Desarrollado por Neftalí Madariaga");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(200, 110, 230, 16);

        jLabel7.setFont(new java.awt.Font("Noto Sans", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Versión 1.0");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(270, 130, 100, 16);

        jLabel8.setFont(new java.awt.Font("Noto Sans", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Universidad Tecnológica Metropolitana");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(190, 160, 250, 16);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoAbout.jpg"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(600, 200));
        jLabel3.setMinimumSize(new java.awt.Dimension(600, 200));
        jLabel3.setPreferredSize(new java.awt.Dimension(600, 200));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 600, 250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
